[server]
headless = true
enableCORS = false
enableXsrfProtection = false
port = 5000
address = "0.0.0.0"
maxUploadSize = 10
enableStaticServing = true

[browser]
gatherUsageStats = false
serverAddress = "0.0.0.0"
serverPort = 5000

[theme]
base = "dark"
backgroundColor = "#0a0a14"
secondaryBackgroundColor = "#14141f"
textColor = "#e8e8f0"
primaryColor = "#FFD700"

[runner]
fastReruns = true

[logger]
level = "warning"
